In [48]:
import numpy as np

## TASK 1
#### Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [49]:
task1 = np.array([i for i in range(10)])
task1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## TASK 2
#### Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [50]:
task2 = np.zeros((3, 3))
task2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## TASK 3
#### Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [51]:
task3 = np.random.randint(1, 11, size=(5,5))
task3

array([[ 7,  9,  3,  9,  8],
       [ 8,  1,  6,  9,  8],
       [ 7, 10,  3,  6,  3],
       [ 9,  6,  5,  3,  4],
       [10, 10,  8,  6, 10]])

## Task 4
#### Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [52]:
task4 = np.random.random(size=(4,4))
task4

array([[0.46298121, 0.80681414, 0.6557204 , 0.85323408],
       [0.19458355, 0.07609641, 0.52998207, 0.97716345],
       [0.09778043, 0.89775575, 0.07816024, 0.02529481],
       [0.18656061, 0.32459145, 0.9652885 , 0.3001804 ]])

## Task 5
#### Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [53]:
array1 = np.random.randint(1,11, size=5)
array2 = np.random.randint(1,11, size=5)
print(f'{array1 = }')
print(f'{array2 = }')

array1 = array([2, 6, 3, 5, 1])
array2 = array([7, 9, 3, 3, 7])


In [54]:
addiction = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
print(f'{addiction = }')
print(f'{subtraction = }')
print(f'{multiplication = }')

addiction = array([ 9, 15,  6,  8,  8])
subtraction = array([-5, -3,  0,  2, -6])
multiplication = array([14, 54,  9, 15,  7])


## Task 6
#### Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [55]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
print(f'{vector1 = }')
print(f'{vector2 = }')

scalar = np.dot(vector1, vector2)
print(f'{scalar = }')


vector1 = array([8.16159387e-01, 3.31745278e-01, 1.16692865e-04, 3.83651556e-01,
       8.36152484e-01, 4.69827524e-01, 5.73455108e-01])
vector2 = array([0.14939287, 0.82861952, 0.51052553, 0.58436956, 0.98648304,
       0.02316311, 0.83101246])
scalar = 1.9333541260069165


## TASK 7
#### Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [56]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print(f'{matrix1 = }')
print(f'{matrix2 = }')

result = np.dot(matrix1, matrix2)
print(f"{result = }")

matrix1 = array([[7, 7],
       [7, 5]])
matrix2 = array([[ 7, 10,  8],
       [ 4,  8,  2]])
result = array([[ 77, 126,  70],
       [ 69, 110,  66]])


## TASK 8
#### Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [57]:
matrix = np.random.randint(1, 11, size=(3,3))
print(f'{matrix = }')

inverse_matrix = np.linalg.inv(matrix)
print(f'{inverse_matrix = }')

matrix = array([[ 4,  6,  3],
       [ 3, 10,  3],
       [ 1,  6, 10]])
inverse_matrix = array([[ 0.43157895, -0.22105263, -0.06315789],
       [-0.14210526,  0.19473684, -0.01578947],
       [ 0.04210526, -0.09473684,  0.11578947]])


## TASK 9
#### Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [58]:
matrix = np.random.randint(1, 11, size=(4,4))
print(f"{matrix = }")

# Transpose the matrix

transposed_matrix= matrix.T
print(f"{transposed_matrix = }")

matrix = array([[ 3,  4,  1,  6],
       [10,  5,  9,  9],
       [ 7,  2,  5,  2],
       [ 4,  9,  7,  5]])
transposed_matrix = array([[ 3, 10,  7,  4],
       [ 4,  5,  2,  9],
       [ 1,  9,  5,  7],
       [ 6,  9,  2,  5]])


## TASK 10
#### Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [59]:
matrix = np.random.randint(1, 11, size=(3,4))
vector = np.random.randint(1, 11, size=(4))

print(f"{matrix = }")
print(f"{vector = }")

result = np.dot(matrix, vector)
print(f"{result = }")

matrix = array([[5, 5, 5, 6],
       [9, 1, 2, 3],
       [5, 7, 3, 4]])
vector = array([9, 3, 3, 6])
result = array([111, 108,  99])


## TASK 11
#### Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [60]:
matrix = np.random.random((2,3))
vector = np.random.random((3))

print(f"{matrix = }")
print(f"{vector = }")

result = np.dot(matrix, vector)
print(f"{result = }")

matrix = array([[0.28330107, 0.54861428, 0.09453146],
       [0.81827145, 0.60505147, 0.80175915]])
vector = array([0.91869762, 0.40316672, 0.22336203])
result = array([0.50256578, 1.17476321])


## TASK 12
#### Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [61]:
matrix1 = np.random.randint(1, 11, size=(2,2))
matrix2 = np.random.randint(1, 11, size=(2,2))

print(f"{matrix1 = }")
print(f"{matrix2 = }")
result = np.multiply(matrix1, matrix2) # result = matrix1 * matrix2
print(f"{result = }")

matrix1 = array([[7, 2],
       [3, 5]])
matrix2 = array([[4, 9],
       [6, 9]])
result = array([[28, 18],
       [18, 45]])


## TASK 13
#### Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [62]:
matrix1 = np.random.randint(1, 11, size=(2,2))
matrix2 = np.random.randint(1, 11, size=(2,2))

print(f"{matrix1 = }")
print(f"{matrix2 = }")
result = np.dot(matrix1, matrix2)
print(f"{result = }")

matrix1 = array([[5, 2],
       [3, 9]])
matrix2 = array([[8, 9],
       [4, 3]])
result = array([[48, 51],
       [60, 54]])


## TASK 14
#### Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [63]:

matrix = np.random.randint(1, 101, size=(5,5))
print(f"{matrix = }")

result = np.sum(matrix)
print(f"{result = }")

matrix = array([[ 26,   5,  93,  26, 100],
       [ 79,  43,  25,  32,  93],
       [ 19,  42,  78,  72,  66],
       [ 15,  19,  66,   7,  70],
       [ 42,  74,  39,  18,  61]])
result = 1210


## TASK 15
#### Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю

In [64]:
matrix1 = np.random.randint(1, 11, size=(4,4))
matrix2 = np.random.randint(1, 11, size=(4,4))

print(f"{matrix1 = }")
print(f"{matrix2 = }")

result = matrix1 - matrix2
print(f"{result = }")

matrix1 = array([[3, 5, 6, 6],
       [4, 4, 9, 1],
       [3, 9, 7, 7],
       [4, 9, 3, 8]])
matrix2 = array([[ 2,  5, 10,  8],
       [ 3,  7,  6,  3],
       [ 2,  7,  9,  9],
       [ 3,  3,  8,  4]])
result = array([[ 1,  0, -4, -2],
       [ 1, -3,  3, -2],
       [ 1,  2, -2, -2],
       [ 1,  6, -5,  4]])


## TASK 16
#### Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [65]:

matrix = np.random.random((3,3))

print(f"{matrix = }")

result = np.sum(matrix, axis=1, keepdims=True)
print(f"{result = }")

matrix = array([[0.24696775, 0.15225333, 0.986883  ],
       [0.09111669, 0.86300956, 0.89522218],
       [0.74194188, 0.63917231, 0.62388824]])
result = array([[1.38610407],
       [1.84934843],
       [2.00500243]])


## TASK 17
#### Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [66]:

matrix = np.random.randint(1, 11, size=(3, 4))

print(f"{matrix = }")

result = np.square(matrix)
print(f"{result = }")

matrix = array([[9, 4, 2, 6],
       [1, 5, 2, 4],
       [9, 5, 2, 4]])
result = array([[81, 16,  4, 36],
       [ 1, 25,  4, 16],
       [81, 25,  4, 16]])


## TASK 18
#### Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [67]:
vector = np.random.randint(1, 51, size=4)

print(f"{vector = }")

result = np.sqrt(vector)
print(f"{result = }")

vector = array([35, 43,  2, 43])
result = array([5.91607978, 6.55743852, 1.41421356, 6.55743852])
